---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  become: true
  gather_facts: false
  tasks:
    - name: Populate service facts
      ansible.builtin.service_facts:

    - name: Ensure opencanary is setup and running
      ansible.builtin.assert:
        that:
          - "'opencanary.service' in ansible_facts.services"
          - '"running" == ansible_facts.services["opencanary.service"].state'
          - '"enabled" == ansible_facts.services["opencanary.service"].status'
